apiVersion: v1
kind: Pod
metadata:
  annotations:
    app: debug
  labels:
    app: debug
  name: debug
spec:
  hostNetwork: true
  containers:
  - image: registry.access.redhat.com/ubi9/ubi-minimal:latest
    imagePullPolicy: IfNotPresent
    name: debug
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
  restartPolicy: Always

