apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ovms
  namespace: openshift-gitops
spec:
  destination:
    namespace: video
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: ovms
    repoURL: https://github.com/yd-ono/Edge-AI-for-video-demo-manifests.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PrunePropagationPolicy=foreground
    - PrunePropagationPolicy=background
    automated:
      prune: true
      selfHeal: true
