apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: openshift-gitops
spec:
  destination:
    namespace: video
    server: https://kubernetes.default.svc
  project: default
  source:
    path: webapp/base
    repoURL: https://github.com/yd-ono/Edge-AI-for-video-demo-manifests.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PrunePropagationPolicy=background
    automated:
      prune: true
      selfHeal: true
