apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: droneai
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: droneai-clusterrole
subjects:
- kind: ServiceAccount
  name: droneai
  namespace: video