apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pipeline-demo-oee-handler
  labels:
    tekton.dev/pipeline: pipeline-demo
spec:
  params:
    - name: target-app-path
      value: webapp
    - name: container-image-name
      value: yolov8-demo
    - name: container-image-version
      value: 1.0
  pipelineRef:
    name: pipeline-demo
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: app-workspace
      persistentVolumeClaim:
        claimName: app-workspace
    - name: manifests-workspace
      persistentVolumeClaim:
        claimName: manifests-workspace
    - name: temp-dir
      persistentVolumeClaim:
        claimName: tempdir