apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: video

images:
- name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: quay.io/yono/droneai
  newTag: "1.0"
