apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ .Values.application.name }}
  namespace: openshift-gitops
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - {{ .Values.application.name }}