apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  namespace: openshift-gitops
  name: {{ .Values.managedclustersetbinding.name }}
spec:
  clusterSet: default