apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    app: {{ .Values.application.name }}
  name: {{ .Values.placement.name }}
  namespace: openshift-gitops
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: 'location'
              operator: 'In'
              values:
                - '{{ .Values.placement.location }}'
  clusterSets:
    - default