apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: {{ .Values.subscription.gitpath}}
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: {{ .Values.application.name }}
  name: {{ .Values.subscription.name }}
  namespace: openshift-gitops
spec:
  channel: "{{ .Values.channel.namespace }}/{{ .Values.channel.name }}"
  placement:
    placementRef:
      kind: Placement
      name: {{ .Values.placement.name }}