apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: appname
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: pipelinerun-demo-
        labels:
          tekton.dev/pipeline: pipeline-demo
      spec:
        params:
          - name: target-app-path
            value: $(tt.params.appname)
          - name: git-app-url
            value: 'https://github.com/yd-ono/Edge-AI-for-video-demo'
          - name: git-app-revision
            value: main
          - name: git-manifests-url
            value: 'https://github.com/yd-ono/Edge-AI-for-video-demo-manifests'
          - name: git-manifests-revision
            value: main
          - name: container-registry-url
            value: 'quay.io/yono'
          - name: container-image-name
            value: 'yolov8-demo'
          - name: container-image-version
            value: 'latest'
        pipelineRef:
          name: pipeline-demo
        taskRunTemplate:
          serviceAccountName: pipeline
        timeouts:
          pipeline: 1h0m0s
        workspaces:
          - name: app-workspace
            persistentVolumeClaim:
              claimName: app-workspace
          - name: manifests-workspace
            persistentVolumeClaim:
              claimName: manifests-workspace
          - name: temp-dir
            persistentVolumeClaim:
              claimName: tempdir