apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tello-mjpeg-streamer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tello-mjpeg-streamer-clusterrole
subjects:
- kind: ServiceAccount
  name: tello-mjpeg-streamer
  namespace: video