apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging

images:
- digest: sha256:d801649d16cf7cb37453d48c6b4891c8a2b6047f0781f24d2273603d7083c54f
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: quay.io/yono/yolov8-demo
