apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-picar
  namespace: openshift-gitops
spec:
  destination:
    namespace: video
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
    path: picar/base
    repoURL: https://github.com/yd-ono/Edge-AI-for-video-demo-manifests.git
    targetRevision: main
  syncPolicy:
    automated: {}
    retry:
      limit: 10
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
