apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging

images:
- digest: sha256:957e8d51074a200bbd9abe1f09b0c409201278760f43b66b84e532e8bb3f8b30
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: quay.io/yono/yolov8-demo
