apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging

images:
- digest: sha256:4a53f4842340ef6ae28147c3f009cb268cd964c94efa518470d06c1c8e4c3904
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: quay.io/yono/yolov8-demo
