apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging

images:
- digest: sha256:5d45b33cf15db787fd8d1d309b6623972cb490424291ede7652c04b8a25675d6
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: quay.io/yono/yolov8-demo
