apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dev

images:
- digest: sha256:ce96d46ca35c5f5911e44fe75814c02664ba3f78391cb0256ab6de1af750c5d0
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: quay.io/yono/yolov8-demo
