apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: picar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: picar-clusterrole
subjects:
- kind: ServiceAccount
  name: picar
  namespace: video