kind: Service
apiVersion: v1
metadata:
  name: picar
  labels:
    app: picar
spec:
  type: NodePort
  ports:
    - name: 5000-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30501
  selector:
    app: picar
