apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: video

images:
- digest: sha256:c8f7d94e46d2516c11fab473e46f4bfd3931a85b4f8ed32333fb88c2a527f5d1
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: quay.io/yono/yolov8-demo
