apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: video

images:
- digest: sha256:07c871c15ffbe2a99adc2441c5e2db05a9e522b93fcd0f3cb909232b44ea592e
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: quay.io/yono/yolov8-demo
