apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: video

images:
- digest: sha256:8788b126f8fb82c71982670847e1754d4b34de1b77d97d4b32521e2ced50006a
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: quay.io/yono/yolov8-demo
