apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: video

images:
- digest: sha256:a581469881282b0a7bd12253e73b0c6a5f51d77ba1445e87c6b635015615f7c2
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: quay.io/yono/yolov8-demo
