apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: video

images:
- digest: sha256:f587ff9972c448eb53799c573e3dcfca894cf807e3930f51008098f9d762c43als
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: quay.io/yono/yolov8-demo
